export const PROPERTY_LIST_REQUEST = 'PROPERTY_LIST_REQUEST'
export const PROPERTY_LIST_SUCCESS = 'PROPERTY_LIST_SUCCESS'
export const PROPERTY_LIST_FAIL = 'PROPERTY_LIST_FAIL'

export const PROPERTY_DETAILS_REQUEST = 'PROPERTY_DETAILS_REQUEST'
export const PROPERTY_DETAILS_SUCCESS = 'PROPERTY_DETAILS_SUCCESS'
export const PROPERTY_DETAILS_FAIL = 'PROPERTY_DETAILS_FAIL'
