export const SHORTLIST_ADD_ITEM = 'SHORTLIST_ADD_ITEM'
export const SHORTLIST_CLEAR_ITEMS = 'SHORTLIST_RESET'
export const SHORTLIST_REMOVE_ITEM = 'SHORTLIST_REMOVE_ITEM'
export const SHORTLIST_ADD_ITEM_REQUEST = 'SHORTLIST_ADD_ITEM_REQUEST'
